#Linnea Inspector
# Copyright (C) 2025
# IRTG-2379: Modern Inverse Problems, RWTH Aachen University, Germany
# HPAC, Umeå University, Sweden

# Contributors:
# - Aravind Sankaran


from setuptools import setup, find_packages
from setuptools.command.install import install

with open("README.md", "r") as f:
    long_description = f.read()

class CustomInstall(install):
    def run(self):
        subprocess.check_call(['git', 'submodule', 'update', '--init', '--recursive'])
        super().run()

setup(
    name='linnea_inspector',
    version="1.0.0",
    description="Linnea Inspector is a tool for synthesising the traces generated by Linnea.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url='',
    author='Aravind Sankaran',
    author_email='aravind.sankaran@rwth-aachen.de',
    packages= find_packages(), # finds packages inside current directory
    classifiers=[
        "Programming Language :: Python :: 3",
    ],
    python_requires=">3",
    #Depends on graphviz and lxml
    install_requires=open("requirements.txt").read().splitlines(),

)